### ISSUE TITLE
AppEngine Flexible liveness_check custom settings not applying

### ISSUE THREAD

**Issue by SacredSkull** [GoogleCloudPlatform/app-maven-plugin#411]
Having a pretty weird issue with an appengine flex deployment pipeline. I've verified that the config going in contains the custom path - as far as I can tell, maven/the appengine plugin is getting all the correct YAML:

```yaml
runtime: java
env: flex

... lots of other params ...

liveness_check:
  path: "/api/someendpoint/liveness_check"
```

Has anyone successfully deployed a custom liveness check using the maven plugin? I've verified that the liveness check is not running correctly through the logs, which indicate that the default liveness check provided by AppEngine itself is being used (`/liveness_check`).

I tried specifying all the defaults along with the custom path, but no difference:

```yaml
liveness_check:
  path: "/api/someendpoint/liveness_check"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
```

I also confirmed that changes to the `app.yaml` file are being reflected in the output (i.e. I changed the runtime to `asdasa` and it broke (as it should).
