### ISSUE TITLE
FR: app.yaml isn't copied to target by default...

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/app-maven-plugin#99]
This means I can't set any environment variables from maven.  The old plugin had this feature.

**Comment by patflynn** [comment]
Hey Les,

Could you include steps to reproduce, and expected behavior?

**Comment by lesv** [comment]
Setup a project with an `src/main/appengine/app.yaml` for example:
```
runtime: java
vm: true
threadsafe: true

handlers:
- url: /.*
  script: this field is required, but ignored
  secure: always

env_variables:
  BIGTABLE_PROJECT:   "${bigtable.projectID}"
  BIGTABLE_INSTANCE:  "${bigtable.instanceID}"
```
In my `pom.xml` set:

      <bigtable.projectID>YOUR_PROJECT_ID</bigtable.projectID>
      <bigtable.instanceID>YOUR_INSTANCE_ID</bigtable.instanceID>

Command line:
`mvn clean package jetty:run -Dbigtable.projectID=xxxxxx-819 -Dbigtable.instanceID=cluster`

I don't find an `app.yaml` anywhere in `target/`, I would expect to, and I used to get that behavior with the old plugin.

**Comment by lesv** [comment]
Note - I should have shown `appengine:run` or `appengine:stage`, still the `app.yaml` in `appengine-staging/`, doesn't have variable substitution set.

```
runtime: java
vm: true
threadsafe: true

handlers:
- url: /.*
  script: this field is required, but ignored
  secure: always

env_variables:
  BIGTABLE_PROJECT:   "${bigtable.projectID}"
  BIGTABLE_INSTANCE:  "${bigtable.instanceID}"
```
